SELECT EMP_NO, EMP_NAME,
CASE WHEN SCORE >= 96 THEN 'S'
    WHEN SCORE >= 90 THEN 'A'
    WHEN SCORE >= 80 THEN 'B'
    ELSE 'C' END 'GRADE',
CASE WHEN SCORE >= 96 THEN SAL * 0.2
    WHEN SCORE >= 90 THEN SAL * 0.15
    WHEN SCORE >= 80 THEN SAL * 0.1
    ELSE 0 END 'BONUS'   
FROM (
    SELECT g.EMP_NO, AVG(g.SCORE) AS SCORE, e.SAL, e.EMP_NAME
    FROM HR_EMPLOYEES e JOIN HR_GRADE g
    ON e.EMP_NO = g.EMP_NO
    GROUP BY g.EMP_NO
) tmp
ORDER BY EMP_NO;