SELECT SUM(g.SCORE) AS SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES e
JOIN HR_GRADE g ON e.EMP_NO = g.EMP_NO
GROUP BY g.YEAR, e.EMP_NO
HAVING g.YEAR = 2022
ORDER BY SCORE DESC
LIMIT 1;